### ISSUE TITLE
Windows builds

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/glue-vispy-viewers-feedstock#1]
From https://github.com/conda-forge/staged-recipes/pull/602#issuecomment-219075595

> @ocefpaf @jakirkham @kmuehlbauer - it looks like the Windows builds are completely missing from https://anaconda.org/conda-forge/glue-vispy-viewers - does this indicate an issue with the skipping of the build for Python 3.5, or does it just take a while for the Windows builds to appear?

@astrofrog the Windows builds are in the queue. See https://ci.appveyor.com/project/conda-forge/glue-vispy-viewers-feedstock/branch/master.

I opened your question as an issue here, in the feedstock, just to show you your recipe new home :wink: 

Feel free to close it.

**Comment by astrofrog** [comment]
@ocefpaf - perfect, thanks! 🏡

**Comment by ocefpaf** [comment]
BTW AppVeyor is backlogged (my bad for merging a ton of PRs) so it might take a while for the Windows builds to finish.
